# Use postgres/example user/password credentials
version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      #PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
      #volumes:
      #- db-data:/var/lib/postgresql/data/pgdata
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
