# Use postgres/example user/password credentials
version: '3'

services:

  app:
    build:
      dockerfile: homework_06/docker-build/Dockerfile
      context: ./
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://user:example@pg:5432/postgres"
    ports:
      - "5000:80"
    volumes:
      - ./homework_06/templates:/app/templates

    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres " ]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  db-data:


